EXAMPLES += Factorial
EXAMPLES += FIFO
EXAMPLES += MeanFilter
EXAMPLES += UnweightedASP
EXAMPLES += UpDownCounter

top:

.PHONY: clean
clean:
	make -C Factorial clean
	make -C FIFO clean
	make -C MeanFilter clean
	make -C UnweightedASP clean
	make -C UpDownCounter clean
	make -C RAM clean
	make -C CPU clean
	make -C Queue clean
	make -C BasicRTL clean
	make -C Sorter clean
	make -C BitScan clean
	make -C Derive clean
