all:

.PHONY: clean
clean:
	make -C CheckAdder clean
	make -C CheckBasicCircuits clean
	make -C CheckQueue clean
	make -C Background clean
	make -C BasicRTL clean
	make -C Bit0 clean
	make -C BitPat clean
	make -C BitScan clean
	make -C CPU clean
	make -C Derive clean
	make -C Factorial clean
	make -C FIFO clean
	make -C Interface clean
	make -C Lookup clean
	make -C MasterSlave clean
	make -C MeanFilter clean
	make -C NameBits clean
	make -C NoC clean
	make -C Option clean
	make -C Queue clean
	make -C RAM clean
	make -C Sklansky clean
	make -C Sorter clean
	make -C SourceSink clean
	make -C Stack clean
	make -C StackTesting clean
	make -C Counter clean
	make -C Vectors clean
	make -C RAMBE clean
