EXAMPLES += Factorial
EXAMPLES += FIFO
EXAMPLES += MeanFilter
EXAMPLES += UnweightedASP
EXAMPLES += UpDownCounter

top:

.PHONY: clean
clean:
	make -C Factorial clean
	make -C NameBits clean
	make -C FIFO clean
	make -C MeanFilter clean
	make -C UpDownCounter clean
	make -C RAM clean
	make -C CPU clean
	make -C Queue clean
	make -C SourceSinkStream clean
	make -C BasicRTL clean
	make -C Sorter clean
	make -C BitScan clean
	make -C BitPat clean
	make -C Derive clean
	make -C Interface clean
	make -C MasterSlave clean
	make -C NoC clean
	make -C Pebbles clean
	make -C Stack clean
	make -C Background clean
	make -C Vectors clean
	make -C OptionExample clean
	make -C StackTesting clean
