#!/bin/bash

if [ -z "$BLARNEY_ROOT" ]; then
  echo "Please set BLARNEY_ROOT"
  exit 1
fi

if [ -z "$1" ]; then
  echo "Usage: blc [FILE].hs"
  exit 1
fi


EXTS="-XScopedTypeVariables -XDataKinds -XTypeOperators -XTypeFamilies"
EXTS="$EXTS -XBinaryLiterals"
INC="$BLARNEY_ROOT/Haskell"
MACROS="$BLARNEY_ROOT/Haskell/Blarney/Macros.h"

ghc -cpp -optP"-include$MACROS" -O $EXTS -i$INC --make $@
