#!/bin/bash

if [ -z "$BLARNEY_ROOT" ]; then
  echo "Please set BLARNEY_ROOT"
  exit 1
fi

if [ -z "$1" ]; then
  echo "Usage: blc [FILE].hs"
  exit 1
fi

GHC="ghc --make"
if [ `basename $0` == "blci" ]; then
  GHC="ghci"
fi

EXTS="-XScopedTypeVariables -XDataKinds -XTypeOperators -XTypeFamilies"
EXTS="$EXTS -XBinaryLiterals -XNoImplicitPrelude -XFlexibleContexts"
EXTS="$EXTS -XRebindableSyntax -XPartialTypeSignatures -XDeriveGeneric"
WARN="-Wno-partial-type-signatures"
INC="$BLARNEY_ROOT/Haskell"
INC_H="$BLARNEY_ROOT/Haskell/Blarney/"
MACROS="$BLARNEY_ROOT/Haskell/Blarney/Macros.h"

$GHC $WARN -cpp -I$INC_H -optP"-include$MACROS" -O $EXTS -i$INC $@
