#! /usr/bin/env bash

if [ -z "$BLARNEY_ROOT" ]; then
  echo "Please set BLARNEY_ROOT"
  exit 1
fi

# Extract command-line flags/arguments
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --enable-namer-plugin)
    USE_NAMER_PLUGIN="YES"
    shift # past argument
    ;;
    *)
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$1" ]; then
  echo "Usage: blc [FLAGS] [FILE].hs"
  echo "Supported flags:"
  echo "  --enable-namer-plugin              Enable Namer plugin"
  exit 1
fi

GHC="ghc --make"
OPT="-O"
if [ `basename $0` == "blci" ]; then
  GHC="ghci"
  OPT=""
fi

EXTS="-XScopedTypeVariables -XDataKinds -XTypeOperators -XTypeFamilies"
EXTS="$EXTS -XBinaryLiterals -XNoImplicitPrelude -XFlexibleContexts"
EXTS="$EXTS -XRebindableSyntax -XPartialTypeSignatures -XDeriveGeneric"
EXTS="$EXTS -XDeriveAnyClass -XRecursiveDo -XBlockArguments"
EXTS="$EXTS -XNumericUnderscores -XTypeApplications"
EXTS="$EXTS -XDuplicateRecordFields -XRankNTypes"
EXTS="$EXTS -XNoStarIsType -XMultiWayIf -XOverloadedRecordDot"
WARN="-Wno-partial-type-signatures"
FLAGS="-fno-cse -fno-full-laziness"
if [ "$USE_NAMER_PLUGIN" = "YES" ]; then
  FLAGS="$FLAGS -package blarney-plugins-namer -fplugin=BlarneyPlugins.Namer"
fi
INC="$BLARNEY_ROOT/Haskell"
INC_H="$BLARNEY_ROOT/Haskell/Blarney/:./"

$GHC $OPT $FLAGS $WARN -cpp -I$INC_H $EXTS -i$INC $@
